export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const SET_COMMENTS_DATA = 'SET_COMMENTS_DATA';
export const SET_COMMENTS_ERROR = 'SET_COMMENTS_ERROR';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
